### ISSUE TITLE
数据库配置

### ISSUE THREAD

**Issue by zero863** [imu-hupeng/SkyRTC#1]
您好，您的应用是使用了mongodb数据库吗，想请问您该如何使用您的项目呢，数据库要如何配置，希望您指导下，不胜感激

**Comment by chmod740** [comment]
我看了下数据库配置在，用的是mongodb
https://github.com/imu-hupeng/SkyRTC/blob/master/server.js#L39
其他的得@shianqi 因为是他写的

**Comment by shianqi** [comment]
@zero863 [README.md](https://github.com/imu-hupeng/SkyRTC) 已更新，可以再看一下，MongoDB 的安装方法可以参考[这里](http://www.runoob.com/mongodb/mongodb-window-install.html)

**Comment by zero863** [comment]
好的，谢谢您啦
